### ISSUE TITLE
Plagiarism as a moral choice

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#37]

**Comment by denaefordrobin** [comment]
Link: http://www.lostgarden.com/2011/11/plagiarism-as-moral-choice.html

This article brings up the interesting point that professional games developers are also professional plagiarists because of the reuse that goes into games without proper citations. This is an interesting aspect to games and  I think it is done in software development too but it is accepted by the community.

It does not discuss the difference from Software Dev to Games Dev. Since it does not express some form of comparison between the two it does not add a dimension.
